package org.example.model;

public enum Operations {

    ADD_EMPLOYEE,
    DELETE_EMPLOYEE,
    EDIT_EMPLOYEE,
    GET_ALL,

    SEARCH_BY_NAME,
    SEARCH_BY_SKILLS,
    FILTER_BY_ROLE,
    FILTER_BY_EXP,
    FILTER_BY_PROJECT,

    SORT_BY_NAME,
    SORT_BY_ROLE,

    GET_STATISTICS,
    GET_TOP_SALARY,
    GET_TOP_EXP,
    GET_HISTORY_TRANSFER,
    GET_SALARY_BY_ID,
    GET_PROJECT_BY_ID,

    LOAD_DATA,
    SAVE_DATA,

    EXIT
}
